version: '3.8'

services:
  haproxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: haproxy
    environment:
      - TZ=Asia/Tashkent
    networks:
      - microservices
    ports:
      - "80:80"
      - "443:443"
      - "8404:8404"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./rsyslog.conf:/etc/rsyslog.conf:ro
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - haproxy_logs:/var/log
    restart: always

  # goaccess:
  #   image: allinurl/goaccess
  #   container_name: goaccess
  #   environment:
  #     - TZ=Asia/Tashkent
  #   depends_on:
  #     - haproxy
  #   volumes:
  #     - haproxy_logs:/var/log:ro
  #     - goaccess_report:/report 
  #   command:
  #     - '/var/log/haproxy.log'
  #     - '--log-format=%h:%^ [%d:%t.%^] %^ %^/%^ %^/%^/%^/%^/%T %s %b %^ %^ %^ %^/%^/%^/%^/%^ %^/%^ "%r"'
  #     - '--date-format=%d/%b/%Y'
  #     - '--time-format=%H:%M:%S'
  #     - '-o'
  #     - '/report/report.html'
  #     - '--real-time-html'
  #     - '--ws-url=ws://185.100.54.28:7890'
  #     - '--port=7890'
  #   ports:
  #     - "7890:7890"

  # webserver:
  #   image: nginx:alpine
  #   container_name: webserver
  #   environment:
  #     - TZ=Asia/Tashkent
  #   depends_on:
  #     - goaccess
  #   volumes:
  #     - goaccess_report:/usr/share/nginx/html:ro  # Use the Docker volume

  #   ports:
  #     - "8022:80"

volumes:
  haproxy_logs:
  # goaccess_report:  # Add this line

networks:
  microservices:
    name: microservices
    external: true
